---
- name: prereq_repos_gather
  hosts: OSEv3
  gather_facts: no
  tasks:
  - name: Query repos
    shell: subscription-manager repos --list-enabled | grep "rhel-7-server-rpms\|rhel-7-server-extras-rpms\|rhel-7-server-optional-rpms\|rhel-7-server-ose-3.2-rpms" | wc -l
    register: query_repos_result
  - name: Query total repos
    shell: subscription-manager repos --list-enabled | grep "Repo ID:" | wc -l
    register: query_total_repos_result

- name: prereq_repos
  hosts: OSEv3
  serial: 1
  gather_facts: no
  tasks:
  - name: Disable repos
    shell: subscription-manager repos --disable="*"
    ignore_errors: yes
    when: query_repos_result.stdout != "4" or query_total_repos_result.stdout != "4"

  - name: Setup extra repos
    command: "subscription-manager repos --enable={{ item }}"
    with_items:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
      - rhel-7-server-ose-3.2-rpms
    when: query_repos_result.stdout != "4" or query_total_repos_result.stdout != "4"
