---
- name: prereq_base_packages
  hosts: OSEv3
  gather_facts: no
  tasks:
  - name: Install base packages
    yum: name={{ item }} state=present
    with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
